# Setup
title:               Galerie Curé-Antoine-Labelle
tagline:             '  la maison de vos projets préférés'
description:         ''
url:                 https://jeremy0levesque.github.io/galeriecal/
baseurl:             '/galeriecal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Marc-Olivier Lacroix
  url:               https://cureantoinelabelle.cslaval.qc.ca/la-pedagogie-a-notre-ecole/option-arts-et-multimedias
  email:             molacroix@cslaval.qc.ca 

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
